# os: linux
# sudo: true
language: go

go:
  - "1.13"

# script:
#   - go build
#   - ./installer
# branches:
#   only:
#     - master

# notifications:
#   email:
# on_success: always
# on_failure: always
